app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/organizer');
});

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', 'Auth\AuthController@logout');

// Registration Routes...
//$this->get('register', 'Auth\AuthController@showRegistrationForm');
//$this->post('register', 'Auth\AuthController@register');

// Password Reset Routes...
$this->get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
$this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
$this->post('password/reset', 'Auth\PasswordController@reset');

//Route::get('/home', 'HomeController@index');


Route::group(['middleware' => 'auth'], function () {


    Route::get('download/{user}', ['as' => 'download', 'uses' => 'UserController@download']);
    Route::get('users', ['as' => 'users', 'uses' => 'UserController@index']);
    Route::get('user/{user}/history', ['as' => 'user.history', 'uses' => 'UserController@history']);
    Route::post('user/upload', ['as' => 'user.upload', 'uses' => 'UserController@upload']);
    Route::get('user/upload', ['as' => 'user.upload', 'uses' => 'UserController@upload']);

    Route::get('user/test', ['as' => 'user.test', 'uses' => 'UserController@parseForm']);
    Route::get('user/parse', ['as' => 'user.parse', 'uses' => 'UserController@parseTest']);

    Route::resource('user', 'UserController');


    //Route::put();
    Route::get('vacancy/{vacancy}/history', ['as' => 'vacancy.history', 'uses' => 'VacancyController@history']);
    Route::get('vacancies', ['as' => 'vacancies', 'uses' => 'VacancyController@index']);
    Route::resource('vacancy', 'VacancyController');


    Route::get('dictionary/toggle', ['as' => 'dictionary.toggle', 'uses' => 'DictionaryController@toggle']);
    Route::resource('dictionary', 'DictionaryController');


    Route::get('companies', ['as' => 'companies', 'uses' => 'CompanyController@index']);
    Route::resource('company', 'CompanyController');
    Route::resource('company', 'CompanyController');


    Route::get('events', ['as' => 'events', 'uses' => 'EventController@index']);
    Route::resource('event', 'EventController');
    Route::get('organizer', ['as' => 'organizer', 'uses' => 'OrganizerController@index']);
    Route::get('organizer/history', ['as' => 'organizer.history', 'uses' => 'OrganizerController@history']);
    Route::get('organizer/events', ['as' => 'organizer.events', 'uses' => 'OrganizerController@events']);


    Route::get('organizer/stickers/{deleted?}', ['as' => 'organizer.stickers', 'uses' => 'OrganizerController@stickers']);
    Route::post('organizer/sticker/store', ['as' => 'sticker.store', 'uses' => 'OrganizerController@stickerSave']);
    Route::put('organizer/sticker/{sticker}', ['as' => 'sticker.update', 'uses' => 'OrganizerController@updateSticker']);
    Route::post('organizer/sticker/{sticker}', ['as' => 'sticker.restore', 'uses' => 'OrganizerController@restoreSticker']);
    Route::delete('organizer/sticker/{sticker}', ['as' => 'sticker.remove', 'uses' => 'OrganizerController@removeSticker']);


    Route::post('candidate/{user}', ['as' => 'setvacancy', 'uses' => 'UserController@setVacancy']);
    Route::resource('candidate', 'CandidateController');


});

app/Vacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\History;

class Vacancy extends Model
{

    use SoftDeletes;
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'salary',
        'currency_id',
        'location_id',
        'lang',
        'requirements',
    ];

    public static $dictionaryFeilds = [
        'currency',
        'location'
    ];

    /**
     * @param $field
     * @return null
     */
    public function dictionaryValue($field)
    {
        if (!in_array($field, self::$dictionaryFeilds)) {
            throw new EntityNotFoundException('Field ".$field." is not dictionary');
        }

        $model = $this->belongsTo(Dictionary::class, null, null, $field)->first();
        if (empty($model)) {
            return null;
        }
        return $model->value;
    }

    /**
     * @return array|null
     */
    public static function getRules()
    {
        static $rules = null;
        if (empty($rules)) {
            $rules = [
                'title' => 'required',
                'currency_id' => 'exists:dictionaries,id|numeric',
                'location_id' => 'exists:dictionaries,id|numeric',
            ];
        }
        return $rules;
    }

    /**
     * @return mixed
     */
    public function history(){
        return $this->hasMany(History::class)->orderBy('created_at', 'desc');
    }
}

app/Http/Controllers/VacancyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Vacancy;
use App\Dictionary;
use App\Http\Requests;
use App\Candidate;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Event;
use App\History;

class VacancyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vacancies = Vacancy::all();
        return view('vacancy.index', ['vacancies' => $vacancies, 'page' => 'vacancies']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->cannot('create', new Vacancy)) {
            abort(403);
        }
        return view('vacancy.create', $this->getFormArgs('VacancyController@store', new Vacancy));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::user()->cannot('create', new Vacancy)) {
            abort(403);
        }

        $this->validate($request, Vacancy::getRules());
        Vacancy::create($request->all());
        return redirect('vacancy');
    }

    /**
     * Display the specified resource.
     *
     * @param  Vacancy $vacancy
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Vacancy $vacancy)
    {
        if (Auth::user()->cannot('read', $vacancy)) {
            abort(403);
        }

        $candidates = Candidate::where('vacancy_id', $vacancy->id)->get();
        $selected = [];
        foreach ($candidates as $candidate) {
            $selected[$candidate->status]['candidates'][] = $candidate;
        }

        $users = User::select(DB::raw('CONCAT(last_name, " ", first_name) AS full_name'), 'id')->whereNotIn('id', Candidate::where('vacancy_id', $vacancy->id)->lists('user_id'))->pluck('full_name', 'id');
        $participants = User::select(DB::raw('CONCAT(last_name, " ", first_name) AS full_name'), 'id')->where('id', '<>', $request->user()->id)->pluck('full_name', 'id');
        return view('vacancy.single', [
            'vacancy' => $vacancy,
            'statuses' => Candidate::getStatus(),
            'selected' => $selected,
            'users' => $users,
            'types' => Event::getTypes(),
            'participants' => $participants,
            'page' => 'vacancy',
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  Vacancy $vacancy
     * @return \Illuminate\Http\Response
     */
    public function edit(Vacancy $vacancy)
    {
        if (Auth::user()->cannot('update', $vacancy)) {
            abort(403);
        }
        return view('vacancy.create', $this->getFormArgs('VacancyController@update', $vacancy));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Vacancy $vacancy
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vacancy $vacancy)
    {
        if (Auth::user()->cannot('update', $vacancy)) {
            abort(403);
        }

        $this->validate($request, Vacancy::getRules());
        $vacancy->update($request->all());
        return redirect('vacancy');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Vacancy $vacancy
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function destroy(Vacancy $vacancy)
    {
        if (Auth::user()->cannot('delete', $vacancy)) {
            abort(403);
        }
        DB::beginTransaction();
        try {
            $vacancy->delete();
        } catch (\Exception $e) {
            DB::rollback();
            throw $e;
        }
        DB::Commit();

        return redirect('vacancy');
    }

   /**
     * @param $action
     * @param Vacancy $vacancy
     * @return array
     */
    protected function getFormArgs($action, Vacancy $vacancy)
    {
        $method = $vacancy->id ? 'put' : 'post';
        $currencies = Dictionary::getDictionary(Dictionary::TYPE_CURRENCY, true);
        $locations = Dictionary::getDictionary(Dictionary::TYPE_LOCATION, true);
        return [
            'vacancy' => $vacancy,
            'action' => $action,
            'method' => $method,
            'locations' => $locations,
            'currencies' => $currencies,
            'page' => 'vacancy-edit',
        ];
    }

    /**
     * @param Request $request
     * @param Vacancy $vacancy
     * @return \Illuminate\Http\JsonResponse
     */
    public function history(Request $request, Vacancy $vacancy)
    {
        if ($request->isMethod('get')) {
            $result = $vacancy->history()->paginate(5);
            $links = empty($result->links()) ? '' : $result->links()->toHtml();

            $response = ['data' => [],
                'links' => $links,
            ];

            $i = 0;
            foreach ($result->getCollection() as $history) {
                $response['data'][$i]['manager'] = $history->manager->last_name . ' ' . $history->manager->first_name;
                $response['data'][$i]['user'] = $history->user->last_name . ' ' . $history->user->first_name;
                $response['data'][$i]['vacancy'] = $history->vacancy->title;
                $response['data'][$i]['old_val'] = $history->old_val ? Candidate::getStatus()[$history->old_val] : '';
                $response['data'][$i]['old_class'] = $history->old_val ? Candidate::getCssClass($history->old_val) : '';
                $response['data'][$i]['new_val'] = $history->new_val ? Candidate::getStatus()[$history->new_val] : '';
                $response['data'][$i]['new_class'] = $history->new_val ? Candidate::getCssClass($history->new_val) : '';
                $response['data'][$i]['action'] = History::getActionType()[$history->action_type];
                $response['data'][$i]['date'] = $history->created_at->format('d.m.y в H:i:s');
                ++$i;
            }

            return response()->json($response);
        }
    }
}

resources/views/vacancy/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-primary add-shadows">
                    <div class="panel-heading">Управление вакансией:</div>
                    <div class="panel-body">
                        {!!Form::model($vacancy,['action'=>[$action, $vacancy->id], 'method'=>$method, 'class'=>'form-horizontal'])!!}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            {!!Form::label('title', 'Вакансия: ', ['class'=>'col-md-4 control-label required'])!!}
                            <div class="col-md-6">
                                {!!Form::text('title', old('title'), ['class'=>'form-control required'])!!}
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('salary') ? ' has-error' : '' }}">
                            {!!Form::label('salary', 'Зарплата: ', ['class'=>'col-md-4 control-label requierd'])!!}
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-7">
                                        {!!Form::number('salary', old('salary'), ['class'=>'form-control'])!!}
                                    </div>
                                    <div class="col-md-5">
                                        {!!Form::select('currency_id', $currencies, old('currency'), ['class'=>'form-control'])!!}
                                    </div>
                                </div>
                                @if ($errors->has('salary'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('salary') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('location_id') ? ' has-error' : '' }}">
                            {!!Form::label('location_id', 'Регион: ', ['class'=>'col-md-4 control-label requierd'])!!}
                            <div class="col-md-6">
                                {!!Form::select('location_id', $locations, old('location_id'), ['class'=>'form-control'])!!}
                                @if ($errors->has('location_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('location_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('lang') ? ' has-error' : '' }}">
                            {!!Form::label('lang', 'Языки: ', ['class'=>'col-md-4 control-label requierd'])!!}
                            <div class="col-md-6">
                                {!!Form::text('lang', old('lang'), ['class'=>'form-control'])!!}
                                @if ($errors->has('lang'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('lang') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('requirements') ? ' has-error' : '' }}">
                            {!!Form::label('requirements', 'Описание: ', ['class'=>'col-md-4 control-label requierd'])!!}
                            <div class="col-md-6">
                                {!!Form::textarea('requirements', old('requirements'), ['class'=>'form-control'])!!}
                                @if ($errors->has('requirements'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('requirements') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <a href="{{route('vacancies')}}" class="btn btn-default">
                                    <i class="fa fa-backward" aria-hidden="true"></i> Назад
                                </a>
                                {!!Form::button('<i class="fa fa-btn fa-user"></i> Создать', ['type'=>'submit', 'class'=>'btn btn-primary pull-right'])!!}
                            </div>
                        </div>

                        {!!Form::close()!!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vacancy/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        @if(session('message'))
            <div class="alert alert-success">
                {{session('message')}}
            </div>
        @endif
    </div>

    {{--<div class="row  search-bar">--}}
        {{--<div class="container-fluid">--}}
            {{--<div class="col-lg-10 col-lg-offset-1">--}}
                {{--<div class="input-group">--}}
                    {{--<span class="input-group-btn">--}}
                        {{--<a class="btn btn-info" href="#">--}}
                            {{--<i class="glyphicon glyphicon-search"></i>--}}
                        {{--</a>--}}
                    {{--</span>--}}
                    {{--<input class="form-control" placeholder="Search for..." type="text">--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}

    <div class="row">
        <div class="container-fluid">
            <div class="col-lg-10 col-lg-offset-1">
                <div class="items-list">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Вакансия</th>
                            <th>З/П</th>
                            <th>Регион</th>
                            <th>Требования</th>
                            @can('update', new \App\Vacancy)
                                <th><i class="fa fa-pencil-square-o" aria-hidden="true"></i></th>
                            @endcan
                            @can('delete', new \App\Vacancy())
                                <th><i class="fa fa-trash" aria-hidden="true"></i></th>
                            @endcan
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($vacancies as $vacancy)
                            <tr>
                                <td>
                                    <a class="item" id="vacancy-title"
                                       href="{{route('vacancy.show', ['id' => $vacancy->id])}}">
                                        {{$vacancy->title}}
                                    </a>
                                </td>
                                <td>{{$vacancy->salary}} {{$vacancy->dictionaryValue('currency')}}</td>
                                <td>{{$vacancy->dictionaryValue('location')}}</td>
                                <td>{{$vacancy->requirements}}</td>
                                @can('update', $vacancy)
                                    <td>
                                        {{Form::open([ 'method'  => 'get', 'route' => [ 'vacancy.edit', $vacancy->id ]])}}
                                        {!!Form::button('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', ['type'=>'submit', 'class'=>'btn btn-xs user-control'])!!}
                                        {!!Form::close()!!}
                                    </td>
                                @endcan
                                @can('delete', new $vacancy)
                                    <td>
                                        {{Form::open([ 'method'  => 'delete', 'class'=>'delete-form', 'route' => [ 'vacancy.destroy', $vacancy->id ]])}}
                                        {!!Form::button('<i class="fa fa-btn fa-trash"></i>', ['type'=>'submit', 'class'=>'btn btn-xs user-control'])!!}
                                        {!!Form::close()!!}
                                    </td>
                                @endcan
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('js/confirm_delete.js')}}"></script>
@endsection

resources/views/vacancy/single.blade.php
@extends('layouts.app')
@section('styles')
    <link rel="stylesheet" href="{!! asset('css/bootstrap-datetimepicker.min.css') !!}">
    <link rel="stylesheet" href="{!! asset('css/bootstrap-select.min.css') !!}">
    <link rel="stylesheet" href="{!! asset('css/bootstrap-colorpicker.min.css') !!}">
@endsection


@section('content')

    <div class="container-fluid">
        <div class="col-md-5">
            <div class="panel panel-primary add-shadows">
                <div class="panel-heading">
                    Вакансия № {{$vacancy->id}}
                    <div class="col-md-1 user-controls pull-right">
                        @can('update', $vacancy)
                            {{Form::open([ 'method'  => 'get', 'route' => [ 'vacancy.edit', $vacancy->id ]])}}
                            {!!Form::button('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', ['type'=>'submit', 'class'=>'btn btn-xs user-control'])!!}
                            {!!Form::close()!!}
                        @endcan
                        @can('delete', $vacancy)
                            {{Form::open([ 'method'  => 'delete', 'route' => [ 'vacancy.destroy', $vacancy->id ]])}}
                            {!!Form::button('<i class="fa fa-btn fa-trash"></i>', ['type'=>'submit', 'class'=>'btn btn-xs user-control'])!!}
                            {!!Form::close()!!}
                        @endcan
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-stripped">
                        <tr>
                            <th class="text-right">Вакансия:</th>
                            <td>
                                <a id="vacancy-title" href="/vacancy/{{$vacancy->id}}/">
                                    {{$vacancy->title}}
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <th class="text-right">З/П:</th>
                            <td>{{$vacancy->salary}} {{$vacancy->dictionaryValue('currency')}}</td>
                        </tr>
                        <tr>
                            <th class="text-right">Регион:</th>
                            <td>{{$vacancy->dictionaryValue('location')}}</td>
                        </tr>
                        <tr>
                            <th class="text-right">Требования:</th>
                            <td>{{$vacancy->requirements}}</td>
                        </tr>
                    </table>
                </div>
            </div>
            @can('create', new \App\Candidate)
                <div class="add-candidates">
                    <a type="button" class="btn btn-success center-block user-single-button add-shadows"
                       data-toggle="modal"
                       data-target="#candidate-select">
                        Подобор кандидатов
                    </a>
                </div>
            @endcan

        </div>
        <div class="col-md-7">

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                @foreach($statuses as $key=>$status)
                    <li class="nav-item">
                        <a class="nav-link {{!$key ? 'active':''}} {{\App\Candidate::getCssClass($key)}}"
                           data-toggle="tab" href="#status-{{$key}}" role="tab">{{$status}}</a>
                    </li>
                @endforeach
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                @foreach($statuses as $key=>$status)
                    <div class="tab-pane {{!$key ? 'active':''}} items-list candidates" id="status-{{$key}}"
                         role="tabpanel">
                        <table class="table table-bordered table-hover candidates-table">
                            <thead>
                            <tr>
                                <th>Имя</th>
                                <th>Зарплата</th>
                                <th>Перемещен</th>
                                <th>Статус</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(isset($selected[$key]))
                                @foreach($selected[$key]['candidates'] as $candidate)
                                    @can('read', $candidate)
                                        <tr id="candidate-{{$candidate->id}}">
                                            <td>
                                                <a id="profile-name"
                                                   href="{{route('user.show', ['id'=>$candidate->user->id])}}">
                                                    {{$candidate->user->last_name . ' ' . $candidate->user->first_name}}
                                                </a>
                                            </td>
                                            <td class="text-center">{{$candidate->user->salary . ' ' . $candidate->user->dictionaryValue('currency')}}</td>
                                            <td class="text-center"><span
                                                        class="label label-info">{{$candidate->updated_at->format('d.m.y в H:i:s')}}</span>
                                            </td>
                                            <td class="text-center">
                                                @can('update', $candidate)
                                                    <button class="btn btn-xs status-label {{\App\Candidate::getCssClass($candidate->status)}}"
                                                            data-status="{{$candidate->status}}">
                                                        {{\App\Candidate::getStatus()[$candidate->status]}}
                                                    </button>
                                                @endcan

                                                @cannot('update', $candidate)
                                                    <label class="btn btn-xs status-label {{\App\Candidate::getCssClass($candidate->status)}}">
                                                        {{\App\Candidate::getStatus()[$candidate->status]}}
                                                    </label>
                                                @endcannot
                                            </td>
                                        </tr>
                                    @endcan
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                        @if(!isset($selected[$key]))
                            <div class="empty">
                                <div class="text-center">Ни один кандидат не был выбран для данной категории</div>
                            </div>
                        @endif
                    </div>
                @endforeach
            </div>
        </div>

    </div>
    <div class="row">
        <div class="container-fluid">
            <div class="row">
                <h3 class="text-center">История изменений:</h3>
            </div>

            <div class="row">
                <div class="container items-list">
                    <table class="table table-striped table-responsive history add-shadows">
                        <thead>
                        <th>Ответственный</th>
                        <th>Действие</th>
                        <th>Кандидат</th>
                        <th>Старый статус</th>
                        <th>Новый статус</th>
                        <th class="text-right">Дата</th>
                        </thead>
                        <tbody id="history_entries">

                        </tbody>
                    </table>

                    <div class="container pagination-container"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal For Candidate Select-->
    @can('create', new \App\Candidate)
        @include('layouts.candidate-select', [
        'modal_id'=>'candidate-select',
        'modal_title'=>'Выберите из списка кандидата:',
        'action'=>'CandidateController@store',
        'action_id'=>null,
        'method'=>'post',
        'start'=>'start-1',
        'end'=>'end-1',
        'color'=>'event-color-1'
        ])
    @endcan

    @can('update', new \App\Candidate)
        <!-- Modal For Status Change-->
        @include('layouts.status-select', [
        'modal_id'=>'status-select',
        'modal_title'=>'Изменить статус для кандидата',
        'action'=>'CandidateController@update',
        'action_id'=>0,
        'method'=>'put',
        'start'=>'start-2',
        'end'=>'end-2',
        'color'=>'event-color-2'
        ])
    @endcan


@endsection

@section('scripts')
    @can('create', new \App\Candidate)
        <script src="{{asset('js/vacancy_candidate_ajax.js')}}"></script>
        <script src="{!! asset('js/moment-with-locales.min.js') !!}"></script>
        <script src="{!! asset('js/bootstrap-datetimepicker.min.js') !!}"></script>
        <script src="{!! asset('js/bootstrap-select.min.js') !!}"></script>
        <script src="{!! asset('js/bootstrap-colorpicker.min.js') !!}"></script>
        <script src="{!! asset('js/event_create.js') !!}"></script>
    @endcan
    <script src="{!! asset('js/single_history.js') !!}"></script>
@endsection