app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/organizer');
});

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', 'Auth\AuthController@logout');

// Registration Routes...
//$this->get('register', 'Auth\AuthController@showRegistrationForm');
//$this->post('register', 'Auth\AuthController@register');

// Password Reset Routes...
$this->get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
$this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
$this->post('password/reset', 'Auth\PasswordController@reset');

//Route::get('/home', 'HomeController@index');


Route::group(['middleware' => 'auth'], function () {


    Route::get('download/{user}', ['as' => 'download', 'uses' => 'UserController@download']);
    Route::get('users', ['as' => 'users', 'uses' => 'UserController@index']);
    Route::get('user/{user}/history', ['as' => 'user.history', 'uses' => 'UserController@history']);
    Route::post('user/upload', ['as' => 'user.upload', 'uses' => 'UserController@upload']);
    Route::get('user/upload', ['as' => 'user.upload', 'uses' => 'UserController@upload']);

    Route::get('user/test', ['as' => 'user.test', 'uses' => 'UserController@parseForm']);
    Route::get('user/parse', ['as' => 'user.parse', 'uses' => 'UserController@parseTest']);

    Route::resource('user', 'UserController');


    //Route::put();
    Route::get('vacancy/{vacancy}/history', ['as' => 'vacancy.history', 'uses' => 'VacancyController@history']);
    Route::get('vacancies', ['as' => 'vacancies', 'uses' => 'VacancyController@index']);
    Route::resource('vacancy', 'VacancyController');


    Route::get('dictionary/toggle', ['as' => 'dictionary.toggle', 'uses' => 'DictionaryController@toggle']);
    Route::resource('dictionary', 'DictionaryController');


    Route::get('companies', ['as' => 'companies', 'uses' => 'CompanyController@index']);
    Route::resource('company', 'CompanyController');
    Route::resource('company', 'CompanyController');


    Route::get('events', ['as' => 'events', 'uses' => 'EventController@index']);
    Route::resource('event', 'EventController');
    Route::get('organizer', ['as' => 'organizer', 'uses' => 'OrganizerController@index']);
    Route::get('organizer/history', ['as' => 'organizer.history', 'uses' => 'OrganizerController@history']);
    Route::get('organizer/events', ['as' => 'organizer.events', 'uses' => 'OrganizerController@events']);


    Route::get('organizer/stickers/{deleted?}', ['as' => 'organizer.stickers', 'uses' => 'OrganizerController@stickers']);
    Route::post('organizer/sticker/store', ['as' => 'sticker.store', 'uses' => 'OrganizerController@stickerSave']);
    Route::put('organizer/sticker/{sticker}', ['as' => 'sticker.update', 'uses' => 'OrganizerController@updateSticker']);
    Route::post('organizer/sticker/{sticker}', ['as' => 'sticker.restore', 'uses' => 'OrganizerController@restoreSticker']);
    Route::delete('organizer/sticker/{sticker}', ['as' => 'sticker.remove', 'uses' => 'OrganizerController@removeSticker']);


    Route::post('candidate/{user}', ['as' => 'setvacancy', 'uses' => 'UserController@setVacancy']);
    Route::resource('candidate', 'CandidateController');


});

resources/views/calendar/create.blade.php
@extends('layouts.app')
@section('styles')
    <link rel="stylesheet" href="{!! asset('css/bootstrap-datetimepicker.min.css') !!}">
    <link rel="stylesheet" href="{!! asset('css/bootstrap-select.min.css') !!}">
    <link rel="stylesheet" href="{!! asset('css/bootstrap-colorpicker.min.css') !!}">
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Создание события</div>
                    <div class="panel-body">
                        {!!Form::model($event,['action'=>[$action, $event->id], 'method'=>$method,'class'=>'form-horizontal'])!!}

                        <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                            {!!Form::label('type', 'Тип события: ', ['class'=>'col-md-4 control-label'])!!}
                            <div class="col-md-6">
                                {!!Form::select('type', $types, old('type'), ['class'=>'form-control'])!!}
                                @if ($errors->has('type'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('type') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}" id="title-div">
                            {!!Form::label('title', 'Заголовок: ', ['class'=>'col-md-4 control-label'])!!}
                            <div class="col-md-6">
                                {!!Form::text('title', old('title'), ['class'=>'form-control required'])!!}
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('color') ? ' has-error' : '' }}">
                            {!!Form::label('color', 'Цвет события: ', ['class'=>'col-md-4 control-label'])!!}
                            <div class="col-md-6">
                                <div id="event-color-1" class="input-group colorpicker-component">
                                    {!!Form::text('color', old('color')?old('color'):'#3399f3', ['class'=>'form-control'])!!}
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                                @if ($errors->has('color'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('color') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            {!!Form::label('description', 'Описание: ', ['class'=>'col-md-4 control-label'])!!}
                            <div class="col-md-6">
                                {!!Form::textarea('description', old('description'), ['class'=>'form-control'])!!}
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        @can('create', new \App\Participant)
                        <div class="form-group{{ $errors->has('participants') ? ' has-error' : '' }}">
                            {!!Form::label('participants', 'Участники: ', ['class'=>'col-md-4 control-label'])!!}
                            <div class="col-md-6">
                                {!!Form::select('participants[]', $participants, $selected, ['class'=>'form-control selectpicker', 'multiple' => 'multiple', "data-live-search"=>"true"])!!}
                                @if ($errors->has('participants'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('participants') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        @endcan


                        <div class="form-group{{ $errors->has('start') || $errors->has('end') ? ' has-error' : '' }}">
                            {!!Form::label('start', 'Время: ', ['class'=>'col-md-4 control-label requierd'])!!}
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class='input-group date' id='start-1'>
                                            {!!Form::text('start', old('start'), ['class'=>'form-control required'])!!}
                                            <span class="input-group-addon"><span
                                                        class="glyphicon glyphicon-calendar"></span></span>
                                            @if ($errors->has('start'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('start') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class='input-group date' id='end-1'>
                                            {!!Form::text('end', old('end'), ['class'=>'form-control required'])!!}
                                            <span class="input-group-addon"><span
                                                        class="glyphicon glyphicon-calendar"></span></span>
                                            @if ($errors->has('end'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('end') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <a href="{{route('events')}}" class="btn btn-default">
                                    <i class="fa fa-backward" aria-hidden="true"></i> Назад
                                </a>
                                {!!Form::button('<i class="fa fa-btn fa-user"></i> Создать', ['type'=>'submit', 'class'=>'btn btn-primary pull-right'])!!}
                            </div>
                        </div>

                        {!!Form::close()!!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{!! asset('js/moment-with-locales.min.js') !!}"></script>
    <script src="{!! asset('js/bootstrap-datetimepicker.min.js') !!}"></script>
    <script src="{!! asset('js/bootstrap-select.min.js') !!}"></script>
    <script src="{!! asset('js/bootstrap-colorpicker.min.js') !!}"></script>
    <script src="{!! asset('js/event_create.js') !!}"></script>
@endsection

resources/views/calendar/index.blade.php
@extends('layouts.app')
@section('styles')
    <link rel="stylesheet" href="{!! asset('css/fullcalendar.min.css') !!}">
@endsection

@section('content')
    <div class="container-fluid">
        <div class="col-md-6 col-md-offset-3">
            <div class="pull-right">
                <a href="{{route('event.create')}}" class="btn btn-primary add-shadows" id="create-event">Добавить событие</a>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="col-md-6 col-md-offset-3">
            {!! $calendar->calendar() !!}
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{!! asset('js/moment-with-locales.min.js') !!}"></script>
    <script src="{!! asset('js/fullcalendar.min.js') !!}"></script>
    {!! $calendar->script() !!}
@endsection

resources/views/calendar/organizer.blade.php
@extends('layouts.app')
@section('styles')
    <link href="https://fonts.googleapis.com/css?family=Marck+Script" rel="stylesheet">
@endsection

@section('content')
    <div class="container-fluid">
        <div class="col-md-5">
            <h4 class="text-center">Предстоящие события:</h4>
            <div class="items-list">
                <table class="table table-striped table-responsive add-shadows" id="upcoming-events">
                    <thead>
                    <th>Тип события</th>
                    <th>Описание</th>
                    <th class="text-right">Дата</th>
                    </thead>
                    <tbody>
                    <tr>
                        <th colspan="3" class="text-center">
                            <img src="{{asset('icon/loading.gif')}}" alt="loading" class="loading">
                        </th>
                    </tr>
                    </tbody>
                </table>
                <div class="container" id="events-pagination"></div>
            </div>
        </div>
        <div class="col-md-7 ">
            <h4 class="text-center">Стикеры:</h4>
            <div id="stickers-container">
                <div class="pull-left" style="padding-right: 15px;">
                    <div class="panel add-shadows" id="stickers-menu">
                        <div class="panel-body" style="min-height: 125px; width: 223px;">
                            <button class="btn btn-success btn-block add-shadows" id="add-sticker" data-toggle="modal"
                                    data-target="#add-sticker-modal">Добавить стикер
                            </button>
                            <button class="btn btn-warning btn-block add-shadows active-stickers" id="toggle-stickers">
                                Закрытые стикеры
                            </button>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12">
                    <div class="container pagination-container" id="stickers-pagination"></div>
                </div>
            </div>
        </div>
    </div>


    </div>
    <div class="container-fluid">
        <h4 class="text-center">Последние действия на сайте:</h4>
        <div class="container-fluid items-list">
            <table class="table table-striped table-responsive history add-shadows">
                <thead>
                <th>Ответственный</th>
                <th>Действие</th>
                <th>Кандидат</th>
                <th>Вакансия</th>
                <th>Старый статус</th>
                <th>Новый статус</th>
                <th class="text-right">Дата</th>
                </thead>
                <tbody id="history_entries">
                <tr>
                    <th colspan="7" class="text-center">
                        <img src="{{asset('icon/loading.gif')}}" alt="loading" class="loading">
                    </th>
                </tr>
                </tbody>
            </table>
            <div class="container pagination-container" id="actions-pagination"></div>
        </div>

    </div>

    <div class="modal fade" id="add-sticker-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Добавить стикер</h4>
                </div>

                {!! Form::open(['action'=>['OrganizerController@stickerSave'], 'method'=>'post', 'class'=>'modal-form', 'id'=>'sticker-form'])!!}

                <div class="modal-body">
                    <div class="row">
                        <div class="form-group {{ $errors->has('sticker_text') ? ' has-error' : '' }}  col-lg-12">
                            {!!Form::label('sticker_text', 'Текст стикера', ['class'=>'col-md-4 control-label class'])!!}
                            <div class="col-md-8 users-select">
                                {!!Form::textarea('sticker_text', null, ['class'=>'form-control', 'cols'=>'50', 'rows'=>'3','style'=>'resize: none'])!!}
                                Осталось символов: <span id="charcounter"></span>
                                @if ($errors->has('sticker_text'))
                                    <span class="help-block">
                                    <strong>{{ $errors->first('sticker_text') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        @can('assign', new \App\Sticker)
                            <div class="form-group{{ $errors->has('addressee_id') ? ' has-error' : '' }}  col-lg-12">
                                {!!Form::label('addressee_id', 'Адресат:', ['class'=>'col-md-4 control-label class add-candidates-modal'])!!}
                                <div class="col-md-8 users-select">
                                    {!!Form::select('addressee_id', $users, Auth::user()->id, ['class'=>'form-control'])!!}
                                    @if ($errors->has('addressee_id'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('addressee_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        @endcan
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    {!! Form::button('Подтвердить', ['type'=>'submit', 'class'=>'btn btn-primary'])!!}
                </div>
                {!!Form::close()!!}
            </div>
        </div>
    </div>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Вы действительно хотите удалить стикер?
                </div>
                <div class="modal-body" id="sticker-content">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <a class="btn btn-danger btn-ok">Удалить</a>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('scripts')
    <script src="{!! asset('js/upcoming_events.js') !!}"></script>
    <script src="{!! asset('js/general_history.js') !!}"></script>
    <script src="{!! asset('js/stickers_ajax.js') !!}"></script>
@endsection

resources/views/calendar/single.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="panel panel-primary add-shadows">
            <div class="panel-heading">
                <i class="fa fa-circle" aria-hidden="true"
                   style="color: {{$event->color}}"></i>&nbsp;&nbsp;&nbsp;{{$event->title}}
                ( {{$event->start->format('d.m H:i')}} - {{$event->end->format('d.m H:i')}} )
                <div class="col-md-1 user-controls pull-right">
                    @can('update', $event)
                        {{Form::open([ 'method'  => 'get', 'route' => [ 'event.edit', $event->id ]])}}
                        {!!Form::button('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', ['type'=>'submit', 'class'=>'btn btn-xs user-control'])!!}
                        {!!Form::close()!!}
                    @endcan
                    @can('delete', $event)
                        {{Form::open([ 'method'  => 'delete', 'route' => [ 'event.destroy', $event->id ]])}}
                        {!!Form::button('<i class="fa fa-btn fa-trash"></i>', ['type'=>'submit', 'class'=>'btn btn-xs user-control'])!!}
                        {!!Form::close()!!}
                    @endcan
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-stripped">
                    <tr>
                        <th>Менеджер:</th>
                        <td>{{$event->manager->last_name}} {{$event->manager->first_name}}</td>
                    </tr>
                    <tr>
                        <th>Описание:</th>
                        <td>{{$event->description}}</td>
                    </tr>
                    <tr>
                        <th>Участники:</th>
                        <td>
                            <ul>
                                @foreach($event->participants as $participant)
                                    <li>
                                        {{$participant->user->last_name}} {{$participant->user->first_name}}
                                    </li>
                                @endforeach
                            </ul>
                        </td>
                    </tr>

                </table>
            </div>
        </div>
    </div>
@endsection