app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/organizer');
});

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', 'Auth\AuthController@logout');

// Registration Routes...
//$this->get('register', 'Auth\AuthController@showRegistrationForm');
//$this->post('register', 'Auth\AuthController@register');

// Password Reset Routes...
$this->get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
$this->post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
$this->post('password/reset', 'Auth\PasswordController@reset');

//Route::get('/home', 'HomeController@index');


Route::group(['middleware' => 'auth'], function () {


    Route::get('download/{user}', ['as' => 'download', 'uses' => 'UserController@download']);
    Route::get('users', ['as' => 'users', 'uses' => 'UserController@index']);
    Route::get('user/{user}/history', ['as' => 'user.history', 'uses' => 'UserController@history']);
    Route::post('user/upload', ['as' => 'user.upload', 'uses' => 'UserController@upload']);
    Route::get('user/upload', ['as' => 'user.upload', 'uses' => 'UserController@upload']);

    Route::get('user/test', ['as' => 'user.test', 'uses' => 'UserController@parseForm']);
    Route::get('user/parse', ['as' => 'user.parse', 'uses' => 'UserController@parseTest']);

    Route::resource('user', 'UserController');


    //Route::put();
    Route::get('vacancy/{vacancy}/history', ['as' => 'vacancy.history', 'uses' => 'VacancyController@history']);
    Route::get('vacancies', ['as' => 'vacancies', 'uses' => 'VacancyController@index']);
    Route::resource('vacancy', 'VacancyController');


    Route::get('dictionary/toggle', ['as' => 'dictionary.toggle', 'uses' => 'DictionaryController@toggle']);
    Route::resource('dictionary', 'DictionaryController');


    Route::get('companies', ['as' => 'companies', 'uses' => 'CompanyController@index']);
    Route::resource('company', 'CompanyController');
    Route::resource('company', 'CompanyController');


    Route::get('events', ['as' => 'events', 'uses' => 'EventController@index']);
    Route::resource('event', 'EventController');
    Route::get('organizer', ['as' => 'organizer', 'uses' => 'OrganizerController@index']);
    Route::get('organizer/history', ['as' => 'organizer.history', 'uses' => 'OrganizerController@history']);
    Route::get('organizer/events', ['as' => 'organizer.events', 'uses' => 'OrganizerController@events']);


    Route::get('organizer/stickers/{deleted?}', ['as' => 'organizer.stickers', 'uses' => 'OrganizerController@stickers']);
    Route::post('organizer/sticker/store', ['as' => 'sticker.store', 'uses' => 'OrganizerController@stickerSave']);
    Route::put('organizer/sticker/{sticker}', ['as' => 'sticker.update', 'uses' => 'OrganizerController@updateSticker']);
    Route::post('organizer/sticker/{sticker}', ['as' => 'sticker.restore', 'uses' => 'OrganizerController@restoreSticker']);
    Route::delete('organizer/sticker/{sticker}', ['as' => 'sticker.remove', 'uses' => 'OrganizerController@removeSticker']);


    Route::post('candidate/{user}', ['as' => 'setvacancy', 'uses' => 'UserController@setVacancy']);
    Route::resource('candidate', 'CandidateController');


});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{csrf_token()}}">
    @if(isset($page))
        <meta name="page" content="{{$page}}">
    @endif
    <title>Faceit-HRM</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css"
          integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="{!! asset('css/bootstrap.min.css') !!}">
    <link rel="stylesheet" href="{!! asset('css/bootstrap-theme.min.css') !!}">


    @yield('styles')
    <link rel="stylesheet" href="{!! asset('css/app.css') !!}">


    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>

</head>
<body id="app-layout">
<nav class="navbar navbar-inverse navbar-static-top">

    <div class="container-fluid navbar-container add-shadows">
        <div class="col-lg-10 col-lg-offset-1">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Faceit-HRM
                </a>
            </div>
            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                @if(Auth::check())
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{{route('organizer')}}" class="{{$page=='organizer'?'current':''}}">Органайзер</a>
                            <a href="{{route('events')}}" class="{{$page=='events'?'current':''}}"><i
                                        class="fa fa-calendar" aria-hidden="true"></i></a>
                        </li>
                        @can('read', new \App\Vacancy)
                            <li>
                                <a href="{{route('vacancies')}}"
                                   class="{{$page=='vacancies'?'current':''}}">Вакансии</a>
                                <span class="sr-only"></span>
                                @can('create', new \App\Vacancy)
                                    <a id="add-vacancy" href="{{route('vacancy.create')}}"
                                       class="{{$page=='vacancy-edit'?'current':''}}">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                    </a>
                                @endcan
                            </li>
                        @endcan
                        @can('read', new \App\User)
                            <li>
                                <a href="{{route('users')}}" class="{{$page=='users'?'current':''}}">Кандидаты</a>
                                @can('create', new \App\User)
                                    <a class="dropdown-toggle {{$page=='user-edit'?'current':''}}" aria-expanded="false"
                                       aria-haspopup="false"
                                       data-toggle="dropdown"
                                       role="button" id="add-candidate" href="#">
                                        <i class="fa fa-th-list" aria-hidden="true"></i>
                                        <span class="caret"></span>
                                    </a>

                                    <ul class="dropdown-menu">
                                        <a class="dropdown-toggle" aria-expanded="false" aria-haspopup="false"
                                           data-toggle="dropdown" role="button" style="color:#ddd;"
                                           id="add-candidate" href="#">
                                        </a>
                                        <li>
                                            <a id="add-candidate" href="{{route('user.create')}}">
                                                <i class="fa fa-plus" aria-hidden="true"></i>
                                                Добавить вручную
                                            </a>
                                        </li>
                                        <li>
                                            <a class="resume_upload" id="upload">
                                                <i class="glyphicon glyphicon-download-alt"></i>
                                                Загрузить из файла
                                            </a>
                                            {!!Form::open(['action'=>'UserController@upload', 'method'=>'post', 'files'=>true, 'hidden'=>'hidden'])!!}
                                            {!!Form::file('cv', null, [])!!}
                                            {!! Form::close() !!}
                                        </li>
                                    </ul>
                                @endcan
                            </li>
                        @endcan
                        @can('read', new \App\Company)
                            <li>
                                <a href="{{route('companies')}}"
                                   class="{{$page=='companies'?'current':''}}">Компании</a>
                                @can('create', new \App\Company)
                                    <a id="add-company" href="{{route('company.create')}}"
                                       class="{{$page=='company-edit'?'current':''}}">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                    </a>
                                @endcan
                            </li>
                        @endcan
                        @can('read', new \App\Dictionary)
                            <li>
                                <a href="{{route('dictionary.index')}}" class="{{$page=='dictionary'?'current':''}}">Словарь</a>
                                @can('create', new \App\Dictionary)
                                    <a id="add-company" href="{{route('dictionary.create')}}"
                                       class="{{$page=='dictionary-edit'?'current':''}}">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                    </a>
                                @endcan
                            </li>
                        @endcan
                    </ul>
            @endif
            <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;Вход</a>
                        </li>
                        {{--<li><a href="{{ url('/register') }}"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;Регистрация</a>--}}
                        {{--</li>--}}
                    @else
                        <li>
                            <a href="{{ url('/user').'/'. Auth::user()->id}}"
                               class="img img-thumbnail nav-avatar add-shadows"
                               style="background-image: url('{{Auth::user()->img_name? asset('uploads/img/'.Auth::user()->id):asset('icon/avatar_dummy.jpg')}}')">
                            </a>
                        </li>
                        <li>
                            <a href="{{ url('/user').'/'. Auth::user()->id}}">
                                <i class="fa fa-user" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;{{Auth::user()->email}}
                            </a>
                        </li>
                        <li>
                            <a href="{{ url('/logout') }}">
                                <i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;Выйти
                            </a>
                        </li>

                        {{--<li class="dropdown">--}}
                        {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">--}}
                        {{--{{ Auth::user()->name }} <span class="caret"></span>--}}
                        {{--</a>--}}

                        {{--<ul class="dropdown-menu" role="menu">--}}
                        {{--<li><a href="{{ url('/logout') }}"><i class="glyphicon glyphicon-off"></i>Выйти</a></li>--}}
                        {{--</ul>--}}
                        {{--</li>--}}
                    @endif
                </ul>
            </div>
        </div>
    </div>


</nav>

@yield('content')

<!-- JavaScripts -->

<script src="{!! asset('js/jquery.min.js') !!}"></script>
<script src="{!! asset('js/bootstrap.min.js') !!}"></script>
<script src="{!! asset('js/upload_cv.js') !!}"></script>

@yield('scripts')
{{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/layouts/candidate-select.blade.php
@extends('layouts.modal')

@section($modal_id)
    {!! Form::hidden('vacancy_id', $vacancy->id)!!}
    <div class="form-group{{ $errors->has('user') ? ' has-error' : '' }}  col-lg-12">
        {!!Form::label('user_id', 'Кандидаты', ['class'=>'col-md-4 control-label class add-candidates-modal'])!!}
        <div class="col-md-8 users-select">
            {!!Form::select('user_id', $users, old('user'), ['class'=>'form-control'])!!}
            @if ($errors->has('user'))
                <span class="help-block">
                <strong>{{ $errors->first('user') }}</strong>
            </span>
            @endif
        </div>
    </div>
@endsection

resources/views/layouts/modal.blade.php
<div class="modal fade" id="{{$modal_id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">{{$modal_title}} <span class="modal-item"></span></h4>
            </div>

            {!! Form::open(['action'=>[$action, $action_id], 'method'=>$method, 'class'=>'modal-form', 'data-method'=>$method])!!}

            <div class="modal-body">
                <div class="row">
                    @yield($modal_id)
                    <div class="form-group {{ $errors->has('interview') ? ' has-error' : '' }}  col-lg-12 inteview-checker">
                        {!!Form::label('interview', 'Назначить собеседование?', ['class'=>'col-md-4 control-label class'])!!}
                        <div class="col-md-8 users-select">
                            {{Form::checkbox('interview', null, null, ['class'=>'appoint-checkbox'])}}
                            @if ($errors->has('interview'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('interview') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                </div>

                <div class="row interview-row">
                    {!! Form::hidden('title', 'Собеседование')!!}
                    <div class="form-group{{ $errors->has('event_color') ? ' has-error' : '' }} col-lg-12">
                        {!!Form::label('color', 'Цвет события: ', ['class'=>'col-md-4 control-label'])!!}
                        <div class="col-md-8">
                            <div id="{{$color}}" class="input-group colorpicker-component">
                                {!!Form::text('color', '#3399f3', ['class'=>'form-control'])!!}
                                <span class="input-group-addon"><i></i></span>
                            </div>
                            @if ($errors->has('color'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('color') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}  col-lg-12">
                        {!!Form::label('description', 'Описание: ', ['class'=>'col-md-4 control-label'])!!}
                        <div class="col-md-8">
                            {!!Form::textarea('description', null, ['class'=>'form-control'])!!}
                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    @can('create', new \App\Participant)
                    <div class="form-group{{ $errors->has('participants') ? ' has-error' : '' }}  col-lg-12">
                        {!!Form::label('participants', 'Участники: ', ['class'=>'col-md-4 control-label'])!!}
                        <div class="col-md-8">
                            {!!Form::select('participants[]', $participants, old('event_participants[]'), ['class'=>'form-control selectpicker', 'multiple' => 'multiple', "data-live-search"=>"true"])!!}
                            @if ($errors->has('participants'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('participants') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    @endcan

                    <div class="form-group{{ $errors->has('start') || $errors->has('end') ? ' has-error' : '' }}  col-lg-12">
                        {!!Form::label('start', 'Время: ', ['class'=>'col-md-4 control-label requierd'])!!}
                        <div class="col-md-8">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class='input-group date start' id='{{$start}}'>
                                        {!!Form::text('start', old('start'), ['class'=>'form-control required'])!!}
                                        <span class="input-group-addon"><span
                                                    class="glyphicon glyphicon-calendar"></span></span>
                                        @if ($errors->has('start'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('event_start') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class='input-group date' id='{{$end}}'>
                                        {!!Form::text('end', old('event_end'), ['class'=>'form-control required'])!!}
                                        <span class="input-group-addon"><span
                                                    class="glyphicon glyphicon-calendar"></span></span>
                                        @if ($errors->has('end'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('end') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                {!! Form::button('Подтвердить', ['type'=>'submit', 'class'=>'btn btn-primary'])!!}
            </div>
            {!!Form::close()!!}
        </div>
    </div>
</div>

resources/views/layouts/status-select.blade.php
@extends('layouts.modal')

@section($modal_id)
    <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}  col-lg-12">
        {!!Form::label('status', 'Статус:', ['class'=>'col-md-4 control-label class add-candidates-modal'])!!}
        <div class="col-md-8 users-select">
            {!! Form::select('status', $statuses, null, ['class'=>'form-control']) !!}
            @if ($errors->has('status'))
                <span class="help-block">
                    <strong>{{ $errors->first('status') }}</strong>
                </span>
            @endif
        </div>
    </div>
@endsection

resources/views/layouts/vacancy-select.blade.php
@extends('layouts.modal')

@section($modal_id)
    {!! Form::hidden('user_id', $user->id)!!}
    <div class="form-group{{ $errors->has('users') ? ' has-error' : '' }}  col-lg-12">
        {!!Form::label('vacancy_id', 'Вакансии', ['class'=>'col-md-4 control-label class add-candidates-modal'])!!}
        <div class="col-md-8 users-select">
            {!!Form::select('vacancy_id', $vacancies, old('vacancy_id'), ['class'=>'form-control'])!!}
            @if ($errors->has('vacancy_id'))
                <span class="help-block">
                <strong>{{ $errors->first('vacancy_id') }}</strong>
            </span>
            @endif
        </div>
    </div>
@endsection